---
title: "Homework 4"
author: GSND 5345Q, Fundamentals of Data Science
date: Due Friday, February 13th, 2026
output: pdf_document
---

Now its time to practice what we have learned in class and learn even more! Note that from now on your homework should be written in R Markdown. Turn in your html file and Rmd files, and any other relevant files in a tarball. Then turn it in by uploading to canvas. 

\subsection*{Data Structures (50 points)}

1.\ (25 points) Learn more about the **scan**, **readLines**, **read\_html**, **readr**, and **readxl** functions for getting data into R. Use these functions to read data from a files into a tibble using R. You can use your own data example or a dataset used in class.  How are these different from the functions we learned in class? Report what you find and give some examples!

2.\	(25 points) Learn about the  **S3**,  **S4**, and  **R6** classes in R. When do you think you would use these? Describe what you learned and give some examples! 

\subsection*{R Markdown (50 points)}

1.\ (25 points) Complete the markdown tutorial at [https://www.markdowntutorial.com/](https://www.markdowntutorial.com/). Confirm here that you completed it (on your honor!). 

2.\ (25 points) R markdown is a powerful tool for literate programming. To gain more practice, as part recreate the `.Rmd` file for the example file in the homework folder: “Rmarkdown_example.html.”
